### ISSUE TITLE
Sniper/Camera zooming bug

### ISSUE THREAD

**Issue by AndreAIsecs12** [gennariarmando/v-hud#35]
Bug while aiming with sniper/camera using scrolling mouse,the game detect as  changing weapon

**Comment by gennariarmando** [comment]
This has been addressed already.

**Comment by AndreAIsecs12** [comment]
i still experienced this tho,except i changing the sniper zoom to R  (zoom in) & G (Zoom Out).
